### ISSUE TITLE
Localize

### ISSUE THREAD

**Issue by MartinAtElitappar** [gabrieltheodoropoulos/EmailComposer#1]
Hi, thanks for a nice work. I am using the EmailComposer in my SwiftUI app. It works great! I am going to localize the app for other languages. My question is if you plan to add support for this? I attach how I use EmailData. 

    var body: some View {
        let emailData = EmailData(subject: "Invitation shared game", recipients: [email], body:
    """
    Hi,
    Click on the attached link to connect.

    \(url!)

    PS.
    Shared play takes place via the internet and Apple iCloud.

    In case of problems check the following:
    - Is there a good connection to the internet?
    - If your team does not appear in the app, click on the attached link again.
    DS.
    """)

**Comment by MartinAtElitappar** [comment]
Hi again, 
I'm a beginner at translation / localization, sorry.. But, I have now found an easy solution to my earlier question. I used a variable instead of static text. For example for the subject: var emailSubject = String(localized: "Invitation shared game").

**Comment by gabrieltheodoropoulos** [comment]
Hi @MartinAtElitappar,
Thank you for using EmailComposer, I'm really glad it's useful for your project! Right now localization related additions are not in my plans, however that's not a problem for you anymore as I understand. What you did to localize your texts is the best and most proper approach, I'd do the same to be honest, so keep going with it.

Thanks again and stay safe!
